#! /bin/sh

bspc monitor -d One Two Three

bspc config border_width        2
bspc config window_gap          10
bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config top_padding         14
bspc config focus_follows_pointer true

bspc config focused_border_color "#009999"
bspc config normal_border_color  "#003366"

panel &
